version: '3.8'

services:
  app:
    build: .
    image: my-spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - mynetwork

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scraping
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge